//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

func main() {
	var client http.Client
	req, err := http.NewRequest("GET", "https://minecraft.wiki/rest.php/v1/page/Module:Protocol_version%2FVersions", nil)
	if err != nil {
		panic(err)
	}
	// TODO: why is this required to avoid a 403 response?
	req.Header.Set("User-Agent", "Go-http-client/1.1")
	res, err := client.Do(req)
	if err != nil {
		panic(err)
	}

	m := make(map[int32][]string)
	re := regexp.MustCompile(`verJE\s*\(\s*java\s*,\s*'([^']+)'\s*,\s*([\dxa-fA-F]+),`)
	scanner := bufio.NewScanner(res.Body)
	scanner.Split(scanEscapedLines)
	for scanner.Scan() {
		s := scanner.Text()
		matches := re.FindStringSubmatch(s)
		if len(matches) > 0 {
			name := matches[1]
			id, found := strings.CutPrefix(matches[2], "0x")
			base := 10
			if found {
				base = 16
			}
			id64, err := strconv.ParseInt(id, base, 32)
			if err != nil {
				panic(err)
			}
			id32 := int32(id64)
			m[id32] = append(m[id32], name)
		}
	}

	ids := make([]int32, 0, len(m))
	for k := range m {
		ids = append(ids, k)
	}
	slices.Sort(ids)

	var b strings.Builder
	b.WriteString("// Code generated by \"go run gen_versions.go\". DO NOT EDIT.\n\npackage mc\n\n")

	b.WriteString("var versionIdName = map[int32]string{\n")
	for _, id := range ids {
		if len(m[id]) == 1 {
			name := formatName(m[id][0])
			fmt.Fprintf(&b, "\t%s: \"%s\",\n", formatId(id), name)
		} else {
			first := formatName(m[id][len(m[id])-1])
			last := formatName(m[id][0])
			fmt.Fprintf(&b, "\t%s: \"%s – %s\",\n", formatId(id), first, last)
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("var versionNameId = map[string]int32{\n")
	for i := len(ids) - 1; i >= 0; i-- {
		if ids[i] < 800 {
			fmt.Fprintf(&b, "\t\"latest\": %s,\n", formatId(ids[i]))
			break
		}
	}
	for _, id := range ids {
		for i := len(m[id]) - 1; i >= 0; i-- {
			name := formatName(m[id][i])
			fmt.Fprintf(&b, "\t\"%s\": %s,\n", name, formatId(id))
		}
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}
	err = os.WriteFile("versions_gen.go", formatted, 0644)
	if err != nil {
		panic(err)
	}
}

func scanEscapedLines(data []byte, atEOF bool) (advance int, token []byte, err error) {
	escaped := false
	for i := range data {
		if escaped && data[i] == 'n' {
			return i + 1, data[0 : i-1], nil
		}
		escaped = data[i] == '\\'
	}
	if atEOF && len(data) > 0 {
		return len(data), data, nil
	}
	return 0, nil, nil
}

func formatId(id int32) string {
	if id < 0x40000000 {
		return fmt.Sprintf("%d", id)
	}
	return fmt.Sprintf("0x%X", id)
}

func formatName(s string) string {
	s = strings.Replace(s, " Pre-Release ", "-pre", 1)
	s = strings.Replace(s, " Pre-release ", "-pre", 1)
	s = strings.Replace(s, " Release Candidate ", "-rc", 1)
	return s
}
